Models/ErrorViewModel.cs
namespace Proiect_MythicTask.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/TODOList.cs
using System.ComponentModel.DataAnnotations;

namespace Proiect_MythicTask.Models
{
    public class TODOList
    {
        [Key]
        public int NrCrit { get; set; }
        [Required]
        public string Obiectiv { get; set;}

        public string Descriere { get; set;}

        public string Locație { get; set;}

        public DateTime Deadline { get; set; } = DateTime.Now;

        public TODOList()
        {
                
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Proiect_MythicTask.Models;
using System.Diagnostics;

namespace Proiect_MythicTask.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TODOListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proiect_MythicTask.Data;
using Proiect_MythicTask.Models;

namespace Proiect_MythicTask.Controllers
{
    public class TODOListsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TODOListsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TODOLists
        [Authorize]
        public async Task<IActionResult> Index()
        {
              return View(await _context.TODOList.ToListAsync());
        }

        // GET: TODOLists // CautareCriteriu
        public async Task<IActionResult> CautareCriteriu()
        {
            return View("CautareCriteriu");
        }

        // POST: TODOLists // RezultateCautareCriteriu
        public async Task<IActionResult> RezultateCautareCriteriu(string CautareDupaLocatie)
        {
            return View("Index", await _context.TODOList.Where(j => j.Locație.Contains(CautareDupaLocatie)).ToListAsync());
        }


        // GET: TODOLists/Details/5
        [Authorize(Roles = "Administrator, Utilizator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TODOList == null)
            {
                return NotFound();
            }

            var tODOList = await _context.TODOList
                .FirstOrDefaultAsync(m => m.NrCrit == id);
            if (tODOList == null)
            {
                return NotFound();
            }

            return View(tODOList);
        }

        // GET: TODOLists/Create
        [Authorize(Roles = "Utilizator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: TODOLists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Utilizator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NrCrit,Obiectiv,Descriere,Locație,Deadline")] TODOList tODOList)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tODOList);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tODOList);
        }

        // GET: TODOLists/Edit/5
        [Authorize(Roles = "Administrator, Utilizator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TODOList == null)
            {
                return NotFound();
            }

            var tODOList = await _context.TODOList.FindAsync(id);
            if (tODOList == null)
            {
                return NotFound();
            }
            return View(tODOList);
        }

        // POST: TODOLists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator, Utilizator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NrCrit,Obiectiv,Descriere,Locație,Deadline")] TODOList tODOList)
        {
            if (id != tODOList.NrCrit)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tODOList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TODOListExists(tODOList.NrCrit))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tODOList);
        }

        // GET: TODOLists/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TODOList == null)
            {
                return NotFound();
            }

            var tODOList = await _context.TODOList
                .FirstOrDefaultAsync(m => m.NrCrit == id);
            if (tODOList == null)
            {
                return NotFound();
            }

            return View(tODOList);
        }

        // POST: TODOLists/Delete/5
        [Authorize(Roles = "Administrator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TODOList == null)
            {
                return Problem("Entity set 'ApplicationDbContext.TODOList'  is null.");
            }
            var tODOList = await _context.TODOList.FindAsync(id);
            if (tODOList != null)
            {
                _context.TODOList.Remove(tODOList);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TODOListExists(int id)
        {
          return _context.TODOList.Any(e => e.NrCrit == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Track your quests!</h1>
    <p><i>"A <b>true</b> hero always keeps track of their tasks and objectives with a trusty to-do list by their side."</i></p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proiect_MythicTask</title>
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Proiect_MythicTask.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Proiect_MythicTask</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (User.IsInRole("Administrator"))
                        {
                            
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Secret Page</a>
                        </li>


                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TODOLists" asp-action="Index">ToDo</a>
                        </li>


                        @if(User.Identity.IsAuthenticated){

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TODOLists" asp-action="CautareCriteriu">Căutare</a>
                        </li>

                        }


                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/TODOLists/CautareCriteriu.cshtml
<h4>Caută un obiectiv după locație</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="RezultateCautareCriteriu">
           
            <div class="form-group">
                <label for="CautareDupaLocatie" class="control-label"></label>
                <input name="CautareDupaLocatie" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Cautare" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Înapoi la listă</a>
</div>

Views/TODOLists/Create.cshtml
@model Proiect_MythicTask.Models.TODOList

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TODOList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Obiectiv" class="control-label"></label>
                <input asp-for="Obiectiv" class="form-control" />
                <span asp-validation-for="Obiectiv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descriere" class="control-label"></label>
                <input asp-for="Descriere" class="form-control" />
                <span asp-validation-for="Descriere" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Locație" class="control-label"></label>
                <input asp-for="Locație" class="form-control" />
                <span asp-validation-for="Locație" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/TODOLists/Delete.cshtml
@model Proiect_MythicTask.Models.TODOList

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TODOList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Obiectiv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Obiectiv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descriere)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descriere)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Locație)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Locație)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deadline)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="NrCrit" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/TODOLists/Details.cshtml
@model Proiect_MythicTask.Models.TODOList

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TODOList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Obiectiv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Obiectiv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descriere)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descriere)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Locație)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Locație)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deadline)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.NrCrit">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/TODOLists/Edit.cshtml
@model Proiect_MythicTask.Models.TODOList

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TODOList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="NrCrit" />
            <div class="form-group">
                <label asp-for="Obiectiv" class="control-label"></label>
                <input asp-for="Obiectiv" class="form-control" />
                <span asp-validation-for="Obiectiv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descriere" class="control-label"></label>
                <input asp-for="Descriere" class="form-control" />
                <span asp-validation-for="Descriere" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Locație" class="control-label"></label>
                <input asp-for="Locație" class="form-control" />
                <span asp-validation-for="Locație" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/TODOLists/Index.cshtml
@model IEnumerable<Proiect_MythicTask.Models.TODOList>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Obiectiv)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.Locație)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deadline)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Obiectiv)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.Locație)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deadline)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.NrCrit">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.NrCrit">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.NrCrit">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>